export const data = [
  {
    id: 1,
    type: ['sincere'],
    popular: 'y',
    email: 'sambo@sambo.com',
    password: '123456789',
    name: '최성준',
    mobile: '010-1234-5678',
    businessName: '동천문화인쇄',
    license:
      'https://lh3.googleusercontent.com/proxy/A4DgLHJqQ1_KaChC7EpdiVoX91s-LhV8t4H1UUsv_G6VlVYEJ7pmYHTfHGyhDpLzo16Sa7-iJX-wfGQQQfw1KHqNn8k6f-igCA2DIS4nyRwVAE-wwQQ8x0HmI2IyZgSL6F_gKSH5c_Ltv-oJWa26XcYEp5mwVOYFaexn1Cs5fsHo-XI',
    cate1: ['1', '0', '2'],
    location: 'seoul',
    description: '카타로그 제작부터 후가공까지 동천문화인쇄에서 제작하세요.',
    popularPart: '패키지, 일반인쇄, 기타인쇄 모두다 제작하고 있습니다.',
    profileImg: [
      'https://www.popwebdesign.net/popart_blog/wp-content/uploads/2016/08/what-is-print-design.png',
      'https://static-cse.canva.com/blob/141577/Print-vs-web_featured-image-final.1ea9dd36.png',
    ],
    bank: {
      name: '국민은행',
      account: '5678-1234-9012345',
      depositor: '최성준',
    },
    rating: 4.5,
  },
  {
    id: 2,
    type: ['sincere', 'popular'],
    popular: 'y',
    email: 'sambo@sambo.com',
    password: '123456789',
    name: '한동준',
    mobile: '010-1234-5678',
    businessName: '한프린터',
    license:
      'https://lh3.googleusercontent.com/proxy/A4DgLHJqQ1_KaChC7EpdiVoX91s-LhV8t4H1UUsv_G6VlVYEJ7pmYHTfHGyhDpLzo16Sa7-iJX-wfGQQQfw1KHqNn8k6f-igCA2DIS4nyRwVAE-wwQQ8x0HmI2IyZgSL6F_gKSH5c_Ltv-oJWa26XcYEp5mwVOYFaexn1Cs5fsHo-XI',
    cate1: ['0'],
    location: 'seoul',
    description: '카타로그 제작부터 후가공까지 한프린터에서 제작하세요.',
    popularPart: '패키지, 일반인쇄, 기타인쇄 모두다 제작하고 있습니다.',
    profileImg: ['http://dmonster1506.cafe24.com/img/noImg.png'],
    bank: {
      name: '국민은행',
      account: '9078-1234-12345',
      depositor: '한동준',
    },
    rating: 4.5,
  },
  {
    id: 3,
    type: ['sincere'],
    popular: 'y',
    email: 'sambo@sambo.com',
    password: '123456789',
    name: '이애리',
    mobile: '010-1234-5678',
    businessName: '스티커천국',
    license:
      'https://lh3.googleusercontent.com/proxy/A4DgLHJqQ1_KaChC7EpdiVoX91s-LhV8t4H1UUsv_G6VlVYEJ7pmYHTfHGyhDpLzo16Sa7-iJX-wfGQQQfw1KHqNn8k6f-igCA2DIS4nyRwVAE-wwQQ8x0HmI2IyZgSL6F_gKSH5c_Ltv-oJWa26XcYEp5mwVOYFaexn1Cs5fsHo-XI',
    cate1: ['0'],
    location: 'busan',
    description: '방수스티커, UV스티커, 소형스티커까지 가능!',
    popularPart: '빠른인쇄! 빈틈없는 색상! 에밀리몰에서 제작하세요!',
    profileImg: [
      'https://diginate.com/media/media/images/Product-Pic-Vinyl-Stickers-Hero-5.jpg',
      'https://d3ccuprjuqkp1j.cloudfront.net/ProductLandingPages/FeaturedImages/SY_CustomStickersMain_720x720_C_20201008160101_0.jpg',
      'https://files.cdn.printful.com/o/upload/lpg-image-upload/11/11bfcfaa204ca22805ba0f31c2aae2fe',
    ],
    bank: {
      name: '국민은행',
      account: '5678-1234-9012345',
      depositor: '스티커천국',
    },
    rating: 4.5,
  },
];
