require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'paper_workshop' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # pod 'react-native-custom-ui-toast', :path => '../node_modules/react-native-custom-ui-toast'

  pod 'GoogleSignIn', '~> 5.0.2'
  pod 'Firebase/Messaging', '~> 7.6.0'

  target 'paper_workshopTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!({ 'Flipper' => '0.74.0' })
#   post_install do |installer|
#     flipper_post_install(installer)
#   end
end

target 'paper_workshop-tvOS' do
  # Pods for paper_workshop-tvOS

  target 'paper_workshop-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
